CREATE TABLE pacientes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    idade NUMBER(3) NOT NULL,
    tipo_dor VARCHAR2(30) NOT NULL,
    tempo_dor NUMBER(4) NOT NULL,
    renda NUMBER(8,2) NOT NULL,
    cep VARCHAR2(10),
    logradouro VARCHAR2(120),
    bairro VARCHAR2(80),
    cidade VARCHAR2(80),
    uf CHAR(2),
    urgencia NUMBER(3) NOT NULL
);

CREATE TABLE dentistas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    especialidade VARCHAR2(40) NOT NULL,
    cep VARCHAR2(10),
    logradouro VARCHAR2(120),
    bairro VARCHAR2(80),
    cidade VARCHAR2(80),
    uf CHAR(2),
    max_pacientes NUMBER(4) NOT NULL,
    atendidos NUMBER(4) DEFAULT 0 NOT NULL
);

CREATE TABLE consultas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id NUMBER NOT NULL,
    dentista_id NUMBER,
    data_consulta VARCHAR2(10) NOT NULL,
    hora_consulta VARCHAR2(5) NOT NULL,
    status VARCHAR2(30) DEFAULT 'AGENDADA' NOT NULL,
    CONSTRAINT fk_consulta_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes(id),
    CONSTRAINT fk_consulta_dentista FOREIGN KEY (dentista_id) REFERENCES dentistas(id)
);
