import json
import os
import re
from datetime import datetime

try:
    import oracledb
except ImportError:
    oracledb = None
    if oracledb:
        oracledb.defaults.thin = True

try:
    import requests
except ImportError:
    requests = None


ARQUIVO_EXPORTACAO_PACIENTES = "consulta_pacientes_urgentes.json"
ARQUIVO_EXPORTACAO_DENTISTAS = "consulta_dentistas_filtrados.json"

ESPECIALIDADES_VALIDAS = [
    "protese",
    "ortodontia",
    "odontopediatria",
    "clinico geral",
    "cirurgia",
    "endodontia",
]

TIPOS_DOR_VALIDOS = ["leve", "forte", "dente quebrado"]


# CONFIGURACAO DO ORACLE
# ORACLE_USER, ORACLE_PASSWORD e ORACLE_DSN.
# Exemplo de DSN: oracle.fiap.com.br:1521/ORCL

ORACLE_USER = os.getenv("ORACLE_USER", "")
ORACLE_PASSWORD = os.getenv("ORACLE_PASSWORD", "")
ORACLE_DSN = os.getenv("ORACLE_DSN", "")


def obter_config_oracle():
    """Pede dados de conexao caso nao estejam em variaveis de ambiente."""
    global ORACLE_USER, ORACLE_PASSWORD, ORACLE_DSN

    if not ORACLE_USER:
        ORACLE_USER = input("Usuario Oracle: ").strip()
    if not ORACLE_PASSWORD:
        ORACLE_PASSWORD = input("Senha Oracle: ").strip()
    if not ORACLE_DSN:
        ORACLE_DSN = input("DSN Oracle (host:porta/service_name): ").strip()


def conectar():
    """Conecta ao banco Oracle."""
    if oracledb is None:
        raise ImportError("Biblioteca 'oracledb' nao instalada. Use: pip install oracledb")
    
    oracledb.defaults.thin = True

    obter_config_oracle()
    return oracledb.connect(
        user=ORACLE_USER,
        password=ORACLE_PASSWORD,
        dsn=ORACLE_DSN,
)


def executar_sql(sql, parametros=None, fetch=False, commit=False):
    """Executa SQL com tratamento centralizado de erro."""
    parametros = parametros or {}
    try:
        with conectar() as conn:
            with conn.cursor() as cursor:
                cursor.execute(sql, parametros)
                if fetch:
                    colunas = [col[0].lower() for col in cursor.description]
                    linhas = cursor.fetchall()
                    return [dict(zip(colunas, linha)) for linha in linhas]
                if commit:
                    conn.commit()
        return []
    except Exception as erro:
        print(f"Erro no banco de dados: {erro}")
        return []


def criar_tabelas():
    """Cria as tabelas da Sprint 4 se elas ainda nao existirem."""
    tabelas = [
        """
        CREATE TABLE pacientes (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome VARCHAR2(100) NOT NULL,
            idade NUMBER(3) NOT NULL,
            tipo_dor VARCHAR2(30) NOT NULL,
            tempo_dor NUMBER(4) NOT NULL,
            renda NUMBER(8,2) NOT NULL,
            cep VARCHAR2(10),
            logradouro VARCHAR2(120),
            bairro VARCHAR2(80),
            cidade VARCHAR2(80),
            uf CHAR(2),
            urgencia NUMBER(3) NOT NULL
        )
        """,
        """
        CREATE TABLE dentistas (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome VARCHAR2(100) NOT NULL,
            especialidade VARCHAR2(40) NOT NULL,
            cep VARCHAR2(10),
            logradouro VARCHAR2(120),
            bairro VARCHAR2(80),
            cidade VARCHAR2(80),
            uf CHAR(2),
            max_pacientes NUMBER(4) NOT NULL,
            atendidos NUMBER(4) DEFAULT 0 NOT NULL
        )
        """,
        """
        CREATE TABLE consultas (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            paciente_id NUMBER NOT NULL,
            dentista_id NUMBER,
            data_consulta VARCHAR2(10) NOT NULL,
            hora_consulta VARCHAR2(5) NOT NULL,
            status VARCHAR2(30) DEFAULT 'AGENDADA' NOT NULL,
            CONSTRAINT fk_consulta_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes(id),
            CONSTRAINT fk_consulta_dentista FOREIGN KEY (dentista_id) REFERENCES dentistas(id)
        )
        """,
    ]

    print("\nCriando/verificando tabelas no Oracle...")
    try:
        with conectar() as conn:
            with conn.cursor() as cursor:
                for sql in tabelas:
                    try:
                        cursor.execute(sql)
                    except Exception as erro:
                        mensagem = str(erro)
                        if "ORA-00955" not in mensagem:
                            raise
            conn.commit()
        print("Tabelas prontas para uso.\n")
    except Exception as erro:
        print(f"Nao foi possivel criar as tabelas: {erro}\n")


# VALIDACOES

def obter_inteiro(mensagem, minimo=None, maximo=None):
    while True:
        try:
            valor = int(input(mensagem))
            if minimo is not None and valor < minimo:
                print(f"Digite um valor maior ou igual a {minimo}.")
                continue
            if maximo is not None and valor > maximo:
                print(f"Digite um valor menor ou igual a {maximo}.")
                continue
            return valor
        except ValueError:
            print("Entrada invalida. Digite um numero inteiro.")


def obter_float(mensagem, minimo=None):
    while True:
        try:
            valor = float(input(mensagem).replace(",", "."))
            if minimo is not None and valor < minimo:
                print(f"Digite um valor maior ou igual a {minimo}.")
                continue
            return valor
        except ValueError:
            print("Entrada invalida. Digite um numero decimal.")


def obter_texto_obrigatorio(mensagem):
    while True:
        texto = input(mensagem).strip()
        if texto:
            return texto
        print("Campo obrigatorio. Tente novamente.")


def obter_opcao_lista(mensagem, opcoes):
    while True:
        valor = input(mensagem).strip().lower()
        if valor in opcoes:
            return valor
        print(f"Opcao invalida. Escolha entre: {', '.join(opcoes)}")


def validar_data(data):
    try:
        datetime.strptime(data, "%d/%m/%Y")
        return True
    except ValueError:
        return False


def validar_hora(hora):
    return re.fullmatch(r"([01]\d|2[0-3]):[0-5]\d", hora) is not None


def obter_data():
    while True:
        data = input("Data da consulta (DD/MM/AAAA): ").strip()
        if validar_data(data):
            return data
        print("Data invalida.")


def obter_hora():
    while True:
        hora = input("Hora da consulta (HH:MM): ").strip()
        if validar_hora(hora):
            return hora
        print("Hora invalida.")


# API PUBLICA: VIACEP

def buscar_cep(cep):
    """Consulta o ViaCEP e retorna os dados de endereco."""
    if requests is None:
        print("Biblioteca 'requests' nao instalada. Use: pip install requests")
        return None

    cep_limpo = re.sub(r"\D", "", cep)
    if len(cep_limpo) != 8:
        print("CEP invalido. Informe 8 numeros.")
        return None

    url = f"https://viacep.com.br/ws/{cep_limpo}/json/"
    try:
        resposta = requests.get(url, timeout=5)
        resposta.raise_for_status()
        dados = resposta.json()

        if dados.get("erro"):
            print("CEP nao encontrado.")
            return None

        return {
            "cep": dados.get("cep", ""),
            "logradouro": dados.get("logradouro", ""),
            "bairro": dados.get("bairro", ""),
            "cidade": dados.get("localidade", ""),
            "uf": dados.get("uf", ""),
        }
    except requests.RequestException as erro:
        print(f"Erro ao consultar API ViaCEP: {erro}")
        return None
    except ValueError:
        print("Resposta invalida da API ViaCEP.")
        return None


def obter_endereco_por_cep():
    """Pede CEP e completa endereco pela API publica ViaCEP."""
    cep = input("CEP (somente numeros ou com hifen): ").strip()
    endereco = buscar_cep(cep)

    if endereco:
        print(
            f"Endereco encontrado: {endereco['logradouro']}, "
            f"{endereco['bairro']} - {endereco['cidade']}/{endereco['uf']}"
        )
        return endereco

    print("Preencha o endereco manualmente.")
    return {
        "cep": cep,
        "logradouro": input("Logradouro: ").strip(),
        "bairro": obter_texto_obrigatorio("Bairro/Cidade: "),
        "cidade": input("Cidade: ").strip(),
        "uf": input("UF: ").strip().upper()[:2],
    }


# REGRAS DO PROJETO

def calcular_urgencia(tipo_dor="leve", tempo_dor=1, renda=1.0, idade=0):
    urgencia = 0

    if tipo_dor == "forte":
        urgencia += 3
    elif tipo_dor == "dente quebrado":
        urgencia += 4
    else:
        urgencia += 1

    if tempo_dor > 7:
        urgencia += 2
    if renda <= 2:
        urgencia += 1
    if 6 <= idade <= 17:
        urgencia += 2
    elif 18 <= idade <= 29:
        urgencia += 1

    return urgencia


def compatibilidade_especialidade(tipo_dor):
    mapa = {
        "leve": ["clinico geral", "odontopediatria"],
        "forte": ["endodontia", "clinico geral"],
        "dente quebrado": ["protese", "cirurgia"],
    }
    return mapa.get(tipo_dor, [])


def encontrar_melhor_dentista(paciente):
    dentistas = executar_sql(
        """
        SELECT id, nome, especialidade, bairro, cidade, uf, max_pacientes, atendidos
        FROM dentistas
        WHERE atendidos < max_pacientes
        """
        ,
        fetch=True,
    )

    melhor = None
    maior_pontuacao = -1
    especialidades = compatibilidade_especialidade(paciente["tipo_dor"])

    for dentista in dentistas:
        pontos = 0
        if dentista["especialidade"] in especialidades:
            pontos += 2
        if dentista.get("bairro") and paciente.get("bairro"):
            if dentista["bairro"].lower() == paciente["bairro"].lower():
                pontos += 3
        if dentista.get("cidade") and paciente.get("cidade"):
            if dentista["cidade"].lower() == paciente["cidade"].lower():
                pontos += 1
        if paciente["urgencia"] >= 5:
            pontos += 5

        if pontos > maior_pontuacao:
            maior_pontuacao = pontos
            melhor = dentista
        elif pontos == maior_pontuacao and melhor:
            if dentista["atendidos"] < melhor["atendidos"]:
                melhor = dentista

    return melhor, maior_pontuacao


# CRUD - PACIENTES

def cadastrar_paciente():
    print("\n--- Cadastrar Paciente ---")
    nome = obter_texto_obrigatorio("Nome do paciente: ")
    idade = obter_inteiro("Idade: ", minimo=0, maximo=120)
    tipo_dor = obter_opcao_lista("Tipo de dor (leve/forte/dente quebrado): ", TIPOS_DOR_VALIDOS)
    tempo_dor = obter_inteiro("Ha quanto tempo sente dor (dias): ", minimo=0)
    renda = obter_float("Renda familiar (em salarios minimos): ", minimo=0)
    endereco = obter_endereco_por_cep()
    urgencia = calcular_urgencia(tipo_dor, tempo_dor, renda, idade)

    executar_sql(
        """
        INSERT INTO pacientes
        (nome, idade, tipo_dor, tempo_dor, renda, cep, logradouro, bairro, cidade, uf, urgencia)
        VALUES
        (:nome, :idade, :tipo_dor, :tempo_dor, :renda, :cep, :logradouro, :bairro, :cidade, :uf, :urgencia)
        """,
        {
            "nome": nome,
            "idade": idade,
            "tipo_dor": tipo_dor,
            "tempo_dor": tempo_dor,
            "renda": renda,
            "cep": endereco["cep"],
            "logradouro": endereco["logradouro"],
            "bairro": endereco["bairro"],
            "cidade": endereco["cidade"],
            "uf": endereco["uf"],
            "urgencia": urgencia,
        },
        commit=True,
    )
    print(f"Paciente '{nome}' cadastrado com urgencia {urgencia}.\n")


def listar_pacientes():
    print("\n--- Lista de Pacientes ---")
    pacientes = executar_sql(
        """
        SELECT id, nome, idade, tipo_dor, tempo_dor, renda, bairro, cidade, uf, urgencia
        FROM pacientes
        ORDER BY id
        """,
        fetch=True,
    )
    if not pacientes:
        print("Nenhum paciente cadastrado.\n")
        return []

    for p in pacientes:
        print(f"[{p['id']}] {p['nome']} | {p['idade']} anos | Urgencia: {p['urgencia']}")
        print(f"    Dor: {p['tipo_dor']} ha {p['tempo_dor']} dias")
        print(f"    Local: {p.get('bairro') or '-'} - {p.get('cidade') or '-'}/{p.get('uf') or '-'}")
        print("-" * 45)
    print(f"Total: {len(pacientes)} paciente(s).\n")
    return pacientes


def consultar_paciente():
    print("\n--- Consultar Paciente ---")
    termo = input("Nome ou parte do nome: ").strip().lower()
    pacientes = executar_sql(
        """
        SELECT id, nome, idade, bairro, cidade, uf, urgencia
        FROM pacientes
        WHERE LOWER(nome) LIKE :termo
        ORDER BY nome
        """,
        {"termo": f"%{termo}%"},
        fetch=True,
    )
    if not pacientes:
        print("Nenhum paciente encontrado.\n")
        return
    for p in pacientes:
        print(f"[{p['id']}] {p['nome']} | {p['idade']} anos | {p['bairro']} - {p['cidade']}/{p['uf']} | Urgencia {p['urgencia']}")
    print()


def editar_paciente():
    print("\n--- Editar Paciente ---")
    listar_pacientes()
    paciente_id = obter_inteiro("ID do paciente a editar (0 para cancelar): ", minimo=0)
    if paciente_id == 0:
        return

    atual = executar_sql(
        "SELECT * FROM pacientes WHERE id = :id",
        {"id": paciente_id},
        fetch=True,
    )
    if not atual:
        print("Paciente nao encontrado.\n")
        return
    p = atual[0]

    print("Pressione Enter para manter o valor atual.")
    nome = input(f"Nome [{p['nome']}]: ").strip() or p["nome"]
    idade_txt = input(f"Idade [{p['idade']}]: ").strip()
    idade = int(idade_txt) if idade_txt.isdigit() else p["idade"]

    tipo_dor = input(f"Tipo de dor [{p['tipo_dor']}]: ").strip().lower() or p["tipo_dor"]
    if tipo_dor not in TIPOS_DOR_VALIDOS:
        print("Tipo de dor invalido. Mantendo valor anterior.")
        tipo_dor = p["tipo_dor"]

    tempo_txt = input(f"Tempo de dor em dias [{p['tempo_dor']}]: ").strip()
    tempo_dor = int(tempo_txt) if tempo_txt.isdigit() else p["tempo_dor"]

    renda_txt = input(f"Renda [{p['renda']}]: ").strip().replace(",", ".")
    if not renda_txt:
     renda = p["renda"]
    else:
      try:
        renda = float(renda_txt)
      except ValueError:
        print("Renda invalida. Mantendo valor anterior.")
        renda = p["renda"]

    alterar_endereco = input("Deseja atualizar endereco por CEP? (s/n): ").strip().lower()
    if alterar_endereco == "s":
        endereco = obter_endereco_por_cep()
    else:
        endereco = {
            "cep": p.get("cep") or "",
            "logradouro": p.get("logradouro") or "",
            "bairro": p.get("bairro") or "",
            "cidade": p.get("cidade") or "",
            "uf": p.get("uf") or "",
        }

    urgencia = calcular_urgencia(tipo_dor, tempo_dor, renda, idade)

    executar_sql(
        """
        UPDATE pacientes
        SET nome = :nome, idade = :idade, tipo_dor = :tipo_dor, tempo_dor = :tempo_dor,
            renda = :renda, cep = :cep, logradouro = :logradouro, bairro = :bairro,
            cidade = :cidade, uf = :uf, urgencia = :urgencia
        WHERE id = :id
        """,
        {
            "id": paciente_id,
            "nome": nome,
            "idade": idade,
            "tipo_dor": tipo_dor,
            "tempo_dor": tempo_dor,
            "renda": renda,
            "cep": endereco["cep"],
            "logradouro": endereco["logradouro"],
            "bairro": endereco["bairro"],
            "cidade": endereco["cidade"],
            "uf": endereco["uf"],
            "urgencia": urgencia,
        },
        commit=True,
    )
    print("Paciente atualizado.\n")


def excluir_paciente():
    print("\n--- Excluir Paciente ---")
    listar_pacientes()
    paciente_id = obter_inteiro("ID do paciente a excluir (0 para cancelar): ", minimo=0)
    if paciente_id == 0:
        return
    confirmar = input("Confirma exclusao? (s/n): ").strip().lower()
    if confirmar != "s":
        print("Exclusao cancelada.\n")
        return
    executar_sql("DELETE FROM consultas WHERE paciente_id = :id", {"id": paciente_id}, commit=True)
    executar_sql("DELETE FROM pacientes WHERE id = :id", {"id": paciente_id}, commit=True)
    print("Paciente excluido.\n")


# CRUD - DENTISTAS

def cadastrar_dentista():
    print("\n--- Cadastrar Dentista ---")
    nome = obter_texto_obrigatorio("Nome do dentista: ")
    especialidade = obter_opcao_lista(
        "Especialidade (protese/ortodontia/odontopediatria/clinico geral/cirurgia/endodontia): ",
        ESPECIALIDADES_VALIDAS,
    )
    endereco = obter_endereco_por_cep()
    max_pacientes = obter_inteiro("Numero maximo de pacientes por mes: ", minimo=1)

    executar_sql(
        """
        INSERT INTO dentistas
        (nome, especialidade, cep, logradouro, bairro, cidade, uf, max_pacientes, atendidos)
        VALUES
        (:nome, :especialidade, :cep, :logradouro, :bairro, :cidade, :uf, :max_pacientes, 0)
        """,
        {
            "nome": nome,
            "especialidade": especialidade,
            "cep": endereco["cep"],
            "logradouro": endereco["logradouro"],
            "bairro": endereco["bairro"],
            "cidade": endereco["cidade"],
            "uf": endereco["uf"],
            "max_pacientes": max_pacientes,
        },
        commit=True,
    )
    print(f"Dentista '{nome}' cadastrado.\n")


def listar_dentistas():
    print("\n--- Lista de Dentistas ---")
    dentistas = executar_sql(
        """
        SELECT id, nome, especialidade, bairro, cidade, uf, max_pacientes, atendidos
        FROM dentistas
        ORDER BY id
        """,
        fetch=True,
    )
    if not dentistas:
        print("Nenhum dentista cadastrado.\n")
        return []

    for d in dentistas:
        vagas = d["max_pacientes"] - d["atendidos"]
        print(f"[{d['id']}] {d['nome']} | {d['especialidade']} | Vagas: {vagas}")
        print(f"    Local: {d.get('bairro') or '-'} - {d.get('cidade') or '-'}/{d.get('uf') or '-'}")
        print("-" * 45)
    print(f"Total: {len(dentistas)} dentista(s).\n")
    return dentistas


def consultar_dentista():
    print("\n--- Consultar Dentista ---")
    print("1. Por nome")
    print("2. Por especialidade")
    opcao = obter_inteiro("Escolha: ", minimo=1, maximo=2)

    if opcao == 1:
        termo = input("Nome ou parte do nome: ").strip().lower()
        sql = """
            SELECT id, nome, especialidade, bairro, cidade, uf, max_pacientes, atendidos
            FROM dentistas
            WHERE LOWER(nome) LIKE :termo
            ORDER BY nome
        """
        params = {"termo": f"%{termo}%"}
    else:
        especialidade = obter_opcao_lista("Especialidade: ", ESPECIALIDADES_VALIDAS)
        sql = """
            SELECT id, nome, especialidade, bairro, cidade, uf, max_pacientes, atendidos
            FROM dentistas
            WHERE especialidade = :especialidade
            ORDER BY nome
        """
        params = {"especialidade": especialidade}

    dentistas = executar_sql(sql, params, fetch=True)
    if not dentistas:
        print("Nenhum dentista encontrado.\n")
        return
    for d in dentistas:
        vagas = d["max_pacientes"] - d["atendidos"]
        print(f"[{d['id']}] {d['nome']} | {d['especialidade']} | {d['bairro']} - {d['cidade']}/{d['uf']} | Vagas {vagas}")
    print()


def editar_dentista():
    print("\n--- Editar Dentista ---")
    listar_dentistas()
    dentista_id = obter_inteiro("ID do dentista a editar (0 para cancelar): ", minimo=0)
    if dentista_id == 0:
        return

    atual = executar_sql("SELECT * FROM dentistas WHERE id = :id", {"id": dentista_id}, fetch=True)
    if not atual:
        print("Dentista nao encontrado.\n")
        return
    d = atual[0]

    print("Pressione Enter para manter o valor atual.")
    nome = input(f"Nome [{d['nome']}]: ").strip() or d["nome"]
    especialidade = input(f"Especialidade [{d['especialidade']}]: ").strip().lower() or d["especialidade"]
    if especialidade not in ESPECIALIDADES_VALIDAS:
        print("Especialidade invalida. Mantendo valor anterior.")
        especialidade = d["especialidade"]

    max_txt = input(f"Maximo de pacientes [{d['max_pacientes']}]: ").strip()
    max_pacientes = int(max_txt) if max_txt.isdigit() else d["max_pacientes"]

    alterar_endereco = input("Deseja atualizar endereco por CEP? (s/n): ").strip().lower()
    if alterar_endereco == "s":
        endereco = obter_endereco_por_cep()
    else:
        endereco = {
            "cep": d.get("cep") or "",
            "logradouro": d.get("logradouro") or "",
            "bairro": d.get("bairro") or "",
            "cidade": d.get("cidade") or "",
            "uf": d.get("uf") or "",
        }

    executar_sql(
        """
        UPDATE dentistas
        SET nome = :nome, especialidade = :especialidade, cep = :cep,
            logradouro = :logradouro, bairro = :bairro, cidade = :cidade,
            uf = :uf, max_pacientes = :max_pacientes
        WHERE id = :id
        """,
        {
            "id": dentista_id,
            "nome": nome,
            "especialidade": especialidade,
            "cep": endereco["cep"],
            "logradouro": endereco["logradouro"],
            "bairro": endereco["bairro"],
            "cidade": endereco["cidade"],
            "uf": endereco["uf"],
            "max_pacientes": max_pacientes,
        },
        commit=True,
    )
    print("Dentista atualizado.\n")


def excluir_dentista():
    print("\n--- Excluir Dentista ---")
    listar_dentistas()
    dentista_id = obter_inteiro("ID do dentista a excluir (0 para cancelar): ", minimo=0)
    if dentista_id == 0:
        return
    confirmar = input("Confirma exclusao? (s/n): ").strip().lower()
    if confirmar != "s":
        print("Exclusao cancelada.\n")
        return
    executar_sql("UPDATE consultas SET dentista_id = NULL WHERE dentista_id = :id", {"id": dentista_id}, commit=True)
    executar_sql("DELETE FROM dentistas WHERE id = :id", {"id": dentista_id}, commit=True)
    print("Dentista excluido.\n")


# CONSULTAS E MATCH

def buscar_paciente_por_id(paciente_id):
    resultado = executar_sql("SELECT * FROM pacientes WHERE id = :id", {"id": paciente_id}, fetch=True)
    return resultado[0] if resultado else None


def buscar_dentista_por_id(dentista_id):
    resultado = executar_sql("SELECT * FROM dentistas WHERE id = :id", {"id": dentista_id}, fetch=True)
    return resultado[0] if resultado else None


def match_paciente_dentista():
    print("\n--- Match Paciente x Dentista ---")
    listar_pacientes()
    paciente_id = obter_inteiro("ID do paciente: ", minimo=1)
    paciente = buscar_paciente_por_id(paciente_id)
    if not paciente:
        print("Paciente nao encontrado.\n")
        return

    dentista, pontuacao = encontrar_melhor_dentista(paciente)
    if dentista and pontuacao > 0:
        print(
            f"Melhor match: {dentista['nome']} | {dentista['especialidade']} | "
            f"Pontuacao: {pontuacao}\n"
        )
    else:
        print("Nenhum dentista compativel disponivel.\n")


def agendar_consulta():
    print("\n--- Agendar Consulta ---")
    listar_pacientes()
    paciente_id = obter_inteiro("ID do paciente: ", minimo=1)
    paciente = buscar_paciente_por_id(paciente_id)
    if not paciente:
        print("Paciente nao encontrado.\n")
        return

    data = obter_data()
    hora = obter_hora()

    usar_match = input("Usar match automatico de dentista? (s/n): ").strip().lower()
    dentista_id = None

    if usar_match == "s":
        dentista, pontuacao = encontrar_melhor_dentista(paciente)
        if dentista and pontuacao > 0:
            dentista_id = dentista["id"]
            print(f"Match realizado: {dentista['nome']} (pontuacao {pontuacao}).")
        else:
            print("Nenhum dentista compativel. Consulta ficara aguardando dentista.")
    else:
        listar_dentistas()
        escolhido = obter_inteiro("ID do dentista (0 para deixar sem dentista): ", minimo=0)
        if escolhido != 0 and buscar_dentista_por_id(escolhido):
            dentista_id = escolhido

    executar_sql(
        """
        INSERT INTO consultas (paciente_id, dentista_id, data_consulta, hora_consulta, status)
        VALUES (:paciente_id, :dentista_id, :data_consulta, :hora_consulta, 'AGENDADA')
        """,
        {
            "paciente_id": paciente_id,
            "dentista_id": dentista_id,
            "data_consulta": data,
            "hora_consulta": hora,
        },
        commit=True,
    )

    if dentista_id:
        executar_sql(
            "UPDATE dentistas SET atendidos = atendidos + 1 WHERE id = :id",
            {"id": dentista_id},
            commit=True,
        )

    print("Consulta agendada.\n")


def listar_consultas():
    print("\n--- Consultas Agendadas ---")
    consultas = executar_sql(
        """
        SELECT c.id, p.nome AS paciente, d.nome AS dentista,
               c.data_consulta, c.hora_consulta, c.status
        FROM consultas c
        JOIN pacientes p ON p.id = c.paciente_id
        LEFT JOIN dentistas d ON d.id = c.dentista_id
        ORDER BY c.id
        """,
        fetch=True,
    )
    if not consultas:
        print("Nenhuma consulta agendada.\n")
        return []

    for c in consultas:
        dentista = c["dentista"] or "Aguardando dentista"
        print(f"[{c['id']}] Paciente: {c['paciente']} | Dentista: {dentista}")
        print(f"    Data/Hora: {c['data_consulta']} as {c['hora_consulta']} | Status: {c['status']}")
        print("-" * 45)
    print(f"Total: {len(consultas)} consulta(s).\n")
    return consultas


def cancelar_consulta():
    print("\n--- Cancelar Consulta ---")
    listar_consultas()
    consulta_id = obter_inteiro("ID da consulta a cancelar (0 para voltar): ", minimo=0)
    if consulta_id == 0:
        return

    consulta = executar_sql(
        "SELECT dentista_id FROM consultas WHERE id = :id",
        {"id": consulta_id},
        fetch=True,
    )
    if not consulta:
        print("Consulta nao encontrada.\n")
        return

    dentista_id = consulta[0].get("dentista_id")
    executar_sql("DELETE FROM consultas WHERE id = :id", {"id": consulta_id}, commit=True)
    if dentista_id:
        executar_sql(
            "UPDATE dentistas SET atendidos = CASE WHEN atendidos > 0 THEN atendidos - 1 ELSE 0 END WHERE id = :id",
            {"id": dentista_id},
            commit=True,
        )
    print("Consulta cancelada.\n")


# CONSULTAS COM FILTROS E EXPORTACAO JSON

def exportar_json(nome_arquivo, dados):
    try:
        with open(nome_arquivo, "w", encoding="utf-8") as arquivo:
            json.dump(dados, arquivo, ensure_ascii=False, indent=4, default=str)
        print(f"Dados exportados para {nome_arquivo}.\n")
    except IOError as erro:
        print(f"Erro ao exportar JSON: {erro}\n")


def consulta_pacientes_por_urgencia():
    print("\n--- Consulta filtrada: Pacientes por urgencia ---")
    urgencia_minima = obter_inteiro("Urgencia minima: ", minimo=0)
    pacientes = executar_sql(
        """
        SELECT id, nome, idade, tipo_dor, tempo_dor, renda, bairro, cidade, uf, urgencia
        FROM pacientes
        WHERE urgencia >= :urgencia
        ORDER BY urgencia DESC, nome
        """,
        {"urgencia": urgencia_minima},
        fetch=True,
    )
    if not pacientes:
        print("Nenhum paciente encontrado para esse filtro.\n")
        return

    for p in pacientes:
        print(f"[{p['id']}] {p['nome']} | Urgencia {p['urgencia']} | {p['bairro']} - {p['cidade']}/{p['uf']}")

    if input("Exportar resultado para JSON? (s/n): ").strip().lower() == "s":
        exportar_json(ARQUIVO_EXPORTACAO_PACIENTES, pacientes)
    print()


def consulta_dentistas_por_filtro():
    print("\n--- Consulta filtrada: Dentistas por bairro/especialidade ---")
    print("1. Filtrar por bairro")
    print("2. Filtrar por especialidade")
    opcao = obter_inteiro("Escolha: ", minimo=1, maximo=2)

    if opcao == 1:
        bairro = obter_texto_obrigatorio("Bairro: ").lower()
        sql = """
            SELECT id, nome, especialidade, bairro, cidade, uf, max_pacientes, atendidos
            FROM dentistas
            WHERE LOWER(bairro) LIKE :bairro
            ORDER BY nome
        """
        params = {"bairro": f"%{bairro}%"}
    else:
        especialidade = obter_opcao_lista("Especialidade: ", ESPECIALIDADES_VALIDAS)
        sql = """
            SELECT id, nome, especialidade, bairro, cidade, uf, max_pacientes, atendidos
            FROM dentistas
            WHERE especialidade = :especialidade
            ORDER BY nome
        """
        params = {"especialidade": especialidade}

    dentistas = executar_sql(sql, params, fetch=True)
    if not dentistas:
        print("Nenhum dentista encontrado para esse filtro.\n")
        return

    for d in dentistas:
        vagas = d["max_pacientes"] - d["atendidos"]
        print(f"[{d['id']}] {d['nome']} | {d['especialidade']} | {d['bairro']} - {d['cidade']}/{d['uf']} | Vagas {vagas}")

    if input("Exportar resultado para JSON? (s/n): ").strip().lower() == "s":
        exportar_json(ARQUIVO_EXPORTACAO_DENTISTAS, dentistas)
    print()


# MENUS

def menu_pacientes():
    while True:
        print("\n=== Gerenciar Pacientes ===")
        print("1. Cadastrar paciente")
        print("2. Listar pacientes")
        print("3. Consultar paciente por nome")
        print("4. Editar paciente")
        print("5. Excluir paciente")
        print("0. Voltar")
        opcao = obter_inteiro("Escolha: ", minimo=0, maximo=5)

        if opcao == 1:
            cadastrar_paciente()
        elif opcao == 2:
            listar_pacientes()
        elif opcao == 3:
            consultar_paciente()
        elif opcao == 4:
            editar_paciente()
        elif opcao == 5:
            excluir_paciente()
        elif opcao == 0:
            break


def menu_dentistas():
    while True:
        print("\n=== Gerenciar Dentistas ===")
        print("1. Cadastrar dentista")
        print("2. Listar dentistas")
        print("3. Consultar dentista")
        print("4. Editar dentista")
        print("5. Excluir dentista")
        print("0. Voltar")
        opcao = obter_inteiro("Escolha: ", minimo=0, maximo=5)

        if opcao == 1:
            cadastrar_dentista()
        elif opcao == 2:
            listar_dentistas()
        elif opcao == 3:
            consultar_dentista()
        elif opcao == 4:
            editar_dentista()
        elif opcao == 5:
            excluir_dentista()
        elif opcao == 0:
            break


def menu_consultas():
    while True:
        print("\n=== Gerenciar Consultas ===")
        print("1. Agendar consulta")
        print("2. Listar consultas")
        print("3. Cancelar consulta")
        print("0. Voltar")
        opcao = obter_inteiro("Escolha: ", minimo=0, maximo=3)

        if opcao == 1:
            agendar_consulta()
        elif opcao == 2:
            listar_consultas()
        elif opcao == 3:
            cancelar_consulta()
        elif opcao == 0:
            break


def menu_relatorios():
    while True:
        print("\n=== Consultas com Filtros e Exportacao JSON ===")
        print("1. Pacientes por urgencia minima")
        print("2. Dentistas por bairro ou especialidade")
        print("0. Voltar")
        opcao = obter_inteiro("Escolha: ", minimo=0, maximo=2)

        if opcao == 1:
            consulta_pacientes_por_urgencia()
        elif opcao == 2:
            consulta_dentistas_por_filtro()
        elif opcao == 0:
            break


def menu():
    while True:
        print("=" * 48)
        print(" DENTISTA NA NUVEM - Sprint 4")
        print(" Oracle Database + API publica ViaCEP")
        print("=" * 48)
        print("1. Gerenciar Pacientes")
        print("2. Gerenciar Dentistas")
        print("3. Match Paciente x Dentista")
        print("4. Gerenciar Consultas")
        print("5. Consultas filtradas e exportacao JSON")
        print("6. Criar/verificar tabelas Oracle")
        print("0. Sair")
        opcao = obter_inteiro("Escolha: ", minimo=0, maximo=6)

        if opcao == 1:
            menu_pacientes()
        elif opcao == 2:
            menu_dentistas()
        elif opcao == 3:
            match_paciente_dentista()
        elif opcao == 4:
            menu_consultas()
        elif opcao == 5:
            menu_relatorios()
        elif opcao == 6:
            criar_tabelas()
        elif opcao == 0:
            print("Encerrando o Dentista na Nuvem. Ate mais!")
            break


if __name__ == "__main__":
    menu()
